server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false


  datasource:
    url: jdbc:mariadb://sideprop.coniu16ba5mz.ap-northeast-2.rds.amazonaws.com/sideCommunity
    username: sidefriends
    password: sidefriends4#
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.ddnc.toy.repository/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.ddnc.toy.domain

